"use client";
import { createContext, useContext, useState, ReactNode } from "react";

export type LangCode = "fr" | "en" | "es" | "de" | "it" | "pt" | "nl" | "no" | "zh" | "ru" | "ar";

export interface Lang {
  code: LangCode;
  label: string;
  flag: string;
  dir: "ltr" | "rtl";
}

export const LANGUAGES: Lang[] = [
  { code: "fr", label: "Francais", flag: "FR", dir: "ltr" },
  { code: "en", label: "English", flag: "EN", dir: "ltr" },
  { code: "es", label: "Espanol", flag: "ES", dir: "ltr" },
  { code: "de", label: "Deutsch", flag: "DE", dir: "ltr" },
  { code: "it", label: "Italiano", flag: "IT", dir: "ltr" },
  { code: "pt", label: "Portugues", flag: "PT", dir: "ltr" },
  { code: "nl", label: "Nederlands", flag: "NL", dir: "ltr" },
  { code: "no", label: "Norsk", flag: "NO", dir: "ltr" },
  { code: "zh", label: "Chinese", flag: "CN", dir: "ltr" },
  { code: "ru", label: "Russian", flag: "RU", dir: "ltr" },
  { code: "ar", label: "Arabic", flag: "AR", dir: "rtl" },
];

export type TranslationKey =
  | "nav_home" | "nav_about" | "nav_services" | "nav_testimonials" | "nav_blog" | "nav_contact" | "nav_consultation"
  | "hero_subtitle" | "hero_title_1" | "hero_title_2" | "hero_title_3" | "hero_desc" | "hero_cta_1" | "hero_cta_2"
  | "about_subtitle" | "about_title_1" | "about_title_2" | "about_p1" | "about_p2" | "about_cta"
  | "services_subtitle" | "services_title" | "services_desc" | "services_cta" | "discover"
  | "values_subtitle" | "values_title_1" | "values_title_2"
  | "journey_subtitle" | "journey_title"
  | "testimonials_subtitle" | "testimonials_title" | "testimonials_cta"
  | "cta_title" | "cta_desc" | "cta_book" | "cta_services"
  | "contact_subtitle" | "contact_title_1" | "contact_title_2"
  | "footer_tagline"
  | "stat_clients" | "stat_years" | "stat_satisfaction" | "stat_services"
  | "chat_greeting" | "chat_placeholder" | "chat_send" | "chat_title" | "chat_subtitle"
  | "chat_q1" | "chat_q2" | "chat_q3" | "chat_q4" | "chat_q5"
  | "chat_a_color" | "chat_a_styling" | "chat_a_pro" | "chat_a_wedding" | "chat_a_other"
  | "chat_name_ask" | "chat_email_ask" | "chat_msg_ask" | "chat_thanks";

type Translations = Record<LangCode, Record<TranslationKey, string>>;

export const T: Translations = {
  fr: {
    nav_home: "Accueil", nav_about: "A Propos", nav_services: "Services",
    nav_testimonials: "Temoignages", nav_blog: "Blog", nav_contact: "Contact",
    nav_consultation: "Consultation",
    hero_subtitle: "Maison de Conseil en Image",
    hero_title_1: "L'Art de Reveler",
    hero_title_2: "Votre Elegance",
    hero_title_3: "Naturelle",
    hero_desc: "Inspiree de l'elegance francaise intemporelle, Maison Oleria vous accompagne dans la revelation de votre style unique.",
    hero_cta_1: "Prendre Rendez-vous", hero_cta_2: "Decouvrir Nos Services",
    about_subtitle: "Notre Histoire", about_title_1: "L'Elegance Francaise", about_title_2: "Sublimee par l'Expertise",
    about_p1: "Maison Oleria est nee d'une conviction profonde : chaque individu porte en lui une elegance unique qui ne demande qu'a etre revelee.",
    about_p2: "Notre approche allie rigueur professionnelle et bienveillance personnelle, pour que chaque transformation soit un voyage vers la meilleure version de vous-meme.",
    about_cta: "Notre Histoire",
    services_subtitle: "Notre Expertise", services_title: "Services de Conseil en Image",
    services_desc: "Un accompagnement complet et personnalise pour chaque facette de votre image personnelle et professionnelle.",
    services_cta: "Tous Nos Services", discover: "Decouvrir",
    values_subtitle: "Nos Valeurs", values_title_1: "Pourquoi Choisir", values_title_2: "Maison Oleria",
    journey_subtitle: "Notre Methode", journey_title: "Votre Parcours de Transformation",
    testimonials_subtitle: "Temoignages", testimonials_title: "Ce Que Disent Nos Clients",
    testimonials_cta: "Tous les Temoignages",
    cta_title: "Prete a Reveler Votre Style ?", cta_desc: "Commencez votre transformation avec une consultation personnalisee.", cta_book: "Reserver Ma Consultation", cta_services: "Voir Nos Formules",
    contact_subtitle: "Nous Contacter", contact_title_1: "Votre Transformation", contact_title_2: "Commence Ici",
    footer_tagline: "L'art de reveler votre style unique a travers l'elegance francaise.",
    stat_clients: "Clients Transformes", stat_years: "Annees d'Experience", stat_satisfaction: "Satisfaction Client", stat_services: "Services Sur Mesure",
    chat_title: "Maison Oleria", chat_subtitle: "Consultante en image", chat_greeting: "Bonjour ! Je suis votre conseillere Maison Oleria. Comment puis-je vous aider aujourd'hui ?",
    chat_placeholder: "Ecrivez votre message...", chat_send: "Envoyer",
    chat_q1: "Quel service vous interesse ?", chat_q2: "En savoir plus sur nos services", chat_q3: "Prendre rendez-vous", chat_q4: "Tarifs et formules", chat_q5: "Envoyer un message",
    chat_a_color: "Analyse Colorimetrique", chat_a_styling: "Stylisme Personnel", chat_a_pro: "Image Professionnelle", chat_a_wedding: "Stylisme Mariage", chat_a_other: "Autre service",
    chat_name_ask: "Quel est votre prenom ?", chat_email_ask: "Votre adresse email ?", chat_msg_ask: "Decrivez votre demande en quelques mots :", chat_thanks: "Merci ! Nous vous recontacterons sous 24h. A tres bientot !",
  },
  en: {
    nav_home: "Home", nav_about: "About", nav_services: "Services",
    nav_testimonials: "Testimonials", nav_blog: "Blog", nav_contact: "Contact",
    nav_consultation: "Consultation",
    hero_subtitle: "Image Consulting House",
    hero_title_1: "The Art of Revealing",
    hero_title_2: "Your Natural",
    hero_title_3: "Elegance",
    hero_desc: "Inspired by timeless French elegance, Maison Oleria guides you in revealing your unique style.",
    hero_cta_1: "Book Appointment", hero_cta_2: "Discover Our Services",
    about_subtitle: "Our Story", about_title_1: "French Elegance", about_title_2: "Elevated by Expertise",
    about_p1: "Maison Oleria was born from a deep conviction: every individual carries a unique elegance that simply needs to be revealed.",
    about_p2: "Our approach combines professional rigor with personal warmth, making every transformation a journey toward your best self.",
    about_cta: "Our Story",
    services_subtitle: "Our Expertise", services_title: "Image Consulting Services",
    services_desc: "Complete and personalized guidance for every aspect of your personal and professional image.",
    services_cta: "All Services", discover: "Discover",
    values_subtitle: "Our Values", values_title_1: "Why Choose", values_title_2: "Maison Oleria",
    journey_subtitle: "Our Method", journey_title: "Your Transformation Journey",
    testimonials_subtitle: "Testimonials", testimonials_title: "What Our Clients Say",
    testimonials_cta: "All Testimonials",
    cta_title: "Ready to Reveal Your Style?", cta_desc: "Start your transformation with a personalized consultation.", cta_book: "Book My Consultation", cta_services: "View Our Packages",
    contact_subtitle: "Contact Us", contact_title_1: "Your Transformation", contact_title_2: "Starts Here",
    footer_tagline: "The art of revealing your unique style through French elegance.",
    stat_clients: "Clients Transformed", stat_years: "Years of Experience", stat_satisfaction: "Client Satisfaction", stat_services: "Bespoke Services",
    chat_title: "Maison Oleria", chat_subtitle: "Image Consultant", chat_greeting: "Hello! I'm your Maison Oleria consultant. How can I help you today?",
    chat_placeholder: "Write your message...", chat_send: "Send",
    chat_q1: "Which service interests you?", chat_q2: "Learn more about our services", chat_q3: "Book an appointment", chat_q4: "Pricing and packages", chat_q5: "Send us a message",
    chat_a_color: "Color Analysis", chat_a_styling: "Personal Styling", chat_a_pro: "Professional Image", chat_a_wedding: "Wedding Styling", chat_a_other: "Other service",
    chat_name_ask: "What is your first name?", chat_email_ask: "Your email address?", chat_msg_ask: "Describe your request in a few words:", chat_thanks: "Thank you! We will contact you within 24 hours. See you soon!",
  },
  es: {
    nav_home: "Inicio", nav_about: "Sobre Nosotros", nav_services: "Servicios",
    nav_testimonials: "Testimonios", nav_blog: "Blog", nav_contact: "Contacto",
    nav_consultation: "Consulta",
    hero_subtitle: "Casa de Consultoria de Imagen",
    hero_title_1: "El Arte de Revelar",
    hero_title_2: "Tu Elegancia",
    hero_title_3: "Natural",
    hero_desc: "Inspirada en la elegancia francesa atemporal, Maison Oleria te acompana en la revelacion de tu estilo unico.",
    hero_cta_1: "Reservar Cita", hero_cta_2: "Descubrir Servicios",
    about_subtitle: "Nuestra Historia", about_title_1: "Elegancia Francesa", about_title_2: "Elevada por la Experiencia",
    about_p1: "Maison Oleria nacio de una profunda conviccion: cada individuo lleva en si una elegancia unica que solo necesita ser revelada.",
    about_p2: "Nuestro enfoque combina rigor profesional con calidez personal, haciendo de cada transformacion un viaje hacia tu mejor version.",
    about_cta: "Nuestra Historia",
    services_subtitle: "Nuestra Experiencia", services_title: "Servicios de Consultoria de Imagen",
    services_desc: "Acompanamiento completo y personalizado para cada aspecto de tu imagen personal y profesional.",
    services_cta: "Todos los Servicios", discover: "Descubrir",
    values_subtitle: "Nuestros Valores", values_title_1: "Por que Elegir", values_title_2: "Maison Oleria",
    journey_subtitle: "Nuestro Metodo", journey_title: "Tu Viaje de Transformacion",
    testimonials_subtitle: "Testimonios", testimonials_title: "Lo Que Dicen Nuestros Clientes",
    testimonials_cta: "Todos los Testimonios",
    cta_title: "Lista para Revelar tu Estilo?", cta_desc: "Comienza tu transformacion con una consulta personalizada.", cta_book: "Reservar Consulta", cta_services: "Ver Paquetes",
    contact_subtitle: "Contactanos", contact_title_1: "Tu Transformacion", contact_title_2: "Comienza Aqui",
    footer_tagline: "El arte de revelar tu estilo unico a traves de la elegancia francesa.",
    stat_clients: "Clientes Transformados", stat_years: "Anos de Experiencia", stat_satisfaction: "Satisfaccion del Cliente", stat_services: "Servicios a Medida",
    chat_title: "Maison Oleria", chat_subtitle: "Consultora de Imagen", chat_greeting: "Hola! Soy tu consultora Maison Oleria. Como puedo ayudarte hoy?",
    chat_placeholder: "Escribe tu mensaje...", chat_send: "Enviar",
    chat_q1: "Que servicio te interesa?", chat_q2: "Saber mas sobre servicios", chat_q3: "Reservar cita", chat_q4: "Precios y paquetes", chat_q5: "Enviar mensaje",
    chat_a_color: "Analisis de Color", chat_a_styling: "Estilismo Personal", chat_a_pro: "Imagen Profesional", chat_a_wedding: "Estilismo de Boda", chat_a_other: "Otro servicio",
    chat_name_ask: "Cual es tu nombre?", chat_email_ask: "Tu correo electronico?", chat_msg_ask: "Describe tu consulta en pocas palabras:", chat_thanks: "Gracias! Te contactaremos en 24 horas. Hasta pronto!",
  },
  de: {
    nav_home: "Startseite", nav_about: "Uber uns", nav_services: "Leistungen",
    nav_testimonials: "Referenzen", nav_blog: "Blog", nav_contact: "Kontakt",
    nav_consultation: "Beratung",
    hero_subtitle: "Image-Beratungshaus",
    hero_title_1: "Die Kunst, Ihre",
    hero_title_2: "Naturliche Eleganz",
    hero_title_3: "Zu Enthullen",
    hero_desc: "Inspiriert von zeitloser franzosischer Eleganz begleitet Maison Oleria Sie bei der Entfaltung Ihres einzigartigen Stils.",
    hero_cta_1: "Termin Buchen", hero_cta_2: "Unsere Leistungen",
    about_subtitle: "Unsere Geschichte", about_title_1: "Franzosische Eleganz", about_title_2: "Erhoht durch Expertise",
    about_p1: "Maison Oleria entstand aus einer tiefen Uberzeugung: Jeder Mensch tragt eine einzigartige Eleganz in sich, die nur darauf wartet, enthullt zu werden.",
    about_p2: "Unser Ansatz verbindet professionelle Sorgfalt mit personlicher Warme, damit jede Transformation eine Reise zu Ihrer besten Version wird.",
    about_cta: "Unsere Geschichte",
    services_subtitle: "Unsere Expertise", services_title: "Image-Beratungsleistungen",
    services_desc: "Vollstandige und personalisierte Begleitung fur jeden Aspekt Ihres personlichen und professionellen Auftretens.",
    services_cta: "Alle Leistungen", discover: "Entdecken",
    values_subtitle: "Unsere Werte", values_title_1: "Warum Maison", values_title_2: "Allure Wahlen",
    journey_subtitle: "Unsere Methode", journey_title: "Ihre Transformationsreise",
    testimonials_subtitle: "Referenzen", testimonials_title: "Was Unsere Kunden Sagen",
    testimonials_cta: "Alle Referenzen",
    cta_title: "Bereit, Ihren Stil zu Enthullen?", cta_desc: "Beginnen Sie Ihre Transformation mit einer personlichen Beratung.", cta_book: "Beratung Buchen", cta_services: "Pakete Ansehen",
    contact_subtitle: "Kontaktieren Sie Uns", contact_title_1: "Ihre Transformation", contact_title_2: "Beginnt Hier",
    footer_tagline: "Die Kunst, Ihren einzigartigen Stil durch franzosische Eleganz zu enthullen.",
    stat_clients: "Transformierte Kunden", stat_years: "Jahre Erfahrung", stat_satisfaction: "Kundenzufriedenheit", stat_services: "Massgeschneiderte Services",
    chat_title: "Maison Oleria", chat_subtitle: "Image-Beraterin", chat_greeting: "Hallo! Ich bin Ihre Maison Oleria Beraterin. Wie kann ich Ihnen heute helfen?",
    chat_placeholder: "Ihre Nachricht...", chat_send: "Senden",
    chat_q1: "Welcher Service interessiert Sie?", chat_q2: "Mehr uber unsere Leistungen", chat_q3: "Termin vereinbaren", chat_q4: "Preise und Pakete", chat_q5: "Nachricht senden",
    chat_a_color: "Farbanalyse", chat_a_styling: "Personliches Styling", chat_a_pro: "Professionelles Image", chat_a_wedding: "Hochzeits-Styling", chat_a_other: "Anderer Service",
    chat_name_ask: "Wie ist Ihr Vorname?", chat_email_ask: "Ihre E-Mail-Adresse?", chat_msg_ask: "Beschreiben Sie Ihr Anliegen kurz:", chat_thanks: "Danke! Wir melden uns innerhalb von 24 Stunden. Bis bald!",
  },
  it: {
    nav_home: "Home", nav_about: "Chi Siamo", nav_services: "Servizi",
    nav_testimonials: "Testimonianze", nav_blog: "Blog", nav_contact: "Contatti",
    nav_consultation: "Consulenza",
    hero_subtitle: "Casa di Consulenza d'Immagine",
    hero_title_1: "L'Arte di Rivelare",
    hero_title_2: "La Tua Eleganza",
    hero_title_3: "Naturale",
    hero_desc: "Ispirata dall'eleganza francese senza tempo, Maison Oleria ti accompagna nella rivelazione del tuo stile unico.",
    hero_cta_1: "Prenota Appuntamento", hero_cta_2: "Scopri i Servizi",
    about_subtitle: "La Nostra Storia", about_title_1: "Eleganza Francese", about_title_2: "Elevata dall'Esperienza",
    about_p1: "Maison Oleria e nata da una profonda convinzione: ogni individuo porta in se un'eleganza unica che aspetta solo di essere rivelata.",
    about_p2: "Il nostro approccio unisce rigore professionale e calore personale, rendendo ogni trasformazione un viaggio verso la tua versione migliore.",
    about_cta: "La Nostra Storia",
    services_subtitle: "La Nostra Esperienza", services_title: "Servizi di Consulenza d'Immagine",
    services_desc: "Accompagnamento completo e personalizzato per ogni aspetto della tua immagine personale e professionale.",
    services_cta: "Tutti i Servizi", discover: "Scoprire",
    values_subtitle: "I Nostri Valori", values_title_1: "Perche Scegliere", values_title_2: "Maison Oleria",
    journey_subtitle: "Il Nostro Metodo", journey_title: "Il Tuo Percorso di Trasformazione",
    testimonials_subtitle: "Testimonianze", testimonials_title: "Cosa Dicono i Nostri Clienti",
    testimonials_cta: "Tutte le Testimonianze",
    cta_title: "Pronta a Rivelare il Tuo Stile?", cta_desc: "Inizia la tua trasformazione con una consulenza personalizzata.", cta_book: "Prenota la Consulenza", cta_services: "Vedi i Pacchetti",
    contact_subtitle: "Contattaci", contact_title_1: "La Tua Trasformazione", contact_title_2: "Inizia Qui",
    footer_tagline: "L'arte di rivelare il tuo stile unico attraverso l'eleganza francese.",
    stat_clients: "Clienti Trasformati", stat_years: "Anni di Esperienza", stat_satisfaction: "Soddisfazione Cliente", stat_services: "Servizi Su Misura",
    chat_title: "Maison Oleria", chat_subtitle: "Consulente d'Immagine", chat_greeting: "Ciao! Sono la tua consulente Maison Oleria. Come posso aiutarti oggi?",
    chat_placeholder: "Scrivi il tuo messaggio...", chat_send: "Invia",
    chat_q1: "Quale servizio ti interessa?", chat_q2: "Scopri i nostri servizi", chat_q3: "Prenota un appuntamento", chat_q4: "Prezzi e pacchetti", chat_q5: "Invia un messaggio",
    chat_a_color: "Analisi del Colore", chat_a_styling: "Styling Personale", chat_a_pro: "Immagine Professionale", chat_a_wedding: "Styling Matrimonio", chat_a_other: "Altro servizio",
    chat_name_ask: "Qual e il tuo nome?", chat_email_ask: "Il tuo indirizzo email?", chat_msg_ask: "Descrivi la tua richiesta in poche parole:", chat_thanks: "Grazie! Ti contatteremo entro 24 ore. A presto!",
  },
  pt: {
    nav_home: "Inicio", nav_about: "Sobre Nos", nav_services: "Servicos",
    nav_testimonials: "Depoimentos", nav_blog: "Blog", nav_contact: "Contato",
    nav_consultation: "Consulta",
    hero_subtitle: "Casa de Consultoria de Imagem",
    hero_title_1: "A Arte de Revelar",
    hero_title_2: "A Sua Elegancia",
    hero_title_3: "Natural",
    hero_desc: "Inspirada na elegancia francesa atemporal, a Maison Oleria acompanha-a na revelacao do seu estilo unico.",
    hero_cta_1: "Marcar Consulta", hero_cta_2: "Descobrir Servicos",
    about_subtitle: "A Nossa Historia", about_title_1: "Elegancia Francesa", about_title_2: "Elevada pela Experiencia",
    about_p1: "A Maison Oleria nasceu de uma convicao profunda: cada individuo carrega uma elegancia unica que apenas precisa de ser revelada.",
    about_p2: "A nossa abordagem combina rigor profissional com calor pessoal, tornando cada transformacao uma viagem rumo a sua melhor versao.",
    about_cta: "A Nossa Historia",
    services_subtitle: "A Nossa Experiencia", services_title: "Servicos de Consultoria de Imagem",
    services_desc: "Acompanhamento completo e personalizado para cada aspeto da sua imagem pessoal e profissional.",
    services_cta: "Todos os Servicos", discover: "Descobrir",
    values_subtitle: "Os Nossos Valores", values_title_1: "Por que Escolher", values_title_2: "Maison Oleria",
    journey_subtitle: "O Nosso Metodo", journey_title: "A Sua Jornada de Transformacao",
    testimonials_subtitle: "Depoimentos", testimonials_title: "O que Dizem os Nossos Clientes",
    testimonials_cta: "Todos os Depoimentos",
    cta_title: "Pronta para Revelar o Seu Estilo?", cta_desc: "Comece a sua transformacao com uma consulta personalizada.", cta_book: "Reservar Consulta", cta_services: "Ver Pacotes",
    contact_subtitle: "Contacte-nos", contact_title_1: "A Sua Transformacao", contact_title_2: "Comeca Aqui",
    footer_tagline: "A arte de revelar o seu estilo unico atraves da elegancia francesa.",
    stat_clients: "Clientes Transformados", stat_years: "Anos de Experiencia", stat_satisfaction: "Satisfacao do Cliente", stat_services: "Servicos a Medida",
    chat_title: "Maison Oleria", chat_subtitle: "Consultora de Imagem", chat_greeting: "Ola! Sou a sua consultora Maison Oleria. Como posso ajuda-la hoje?",
    chat_placeholder: "Escreva a sua mensagem...", chat_send: "Enviar",
    chat_q1: "Qual servico lhe interessa?", chat_q2: "Saber mais sobre servicos", chat_q3: "Marcar consulta", chat_q4: "Precos e pacotes", chat_q5: "Enviar mensagem",
    chat_a_color: "Analise de Cor", chat_a_styling: "Styling Pessoal", chat_a_pro: "Imagem Profissional", chat_a_wedding: "Styling de Casamento", chat_a_other: "Outro servico",
    chat_name_ask: "Qual e o seu nome?", chat_email_ask: "O seu email?", chat_msg_ask: "Descreva o seu pedido em poucas palavras:", chat_thanks: "Obrigado! Entraremos em contacto em 24 horas. Ate breve!",
  },
  nl: {
    nav_home: "Home", nav_about: "Over Ons", nav_services: "Diensten",
    nav_testimonials: "Getuigenissen", nav_blog: "Blog", nav_contact: "Contact",
    nav_consultation: "Consultatie",
    hero_subtitle: "Beeldadviesbureau",
    hero_title_1: "De Kunst van het Onthullen",
    hero_title_2: "van Uw Natuurlijke",
    hero_title_3: "Elegantie",
    hero_desc: "Geinspireerd door tijdloze Franse elegantie begeleidt Maison Oleria u bij het ontdekken van uw unieke stijl.",
    hero_cta_1: "Afspraak Maken", hero_cta_2: "Ontdek Onze Diensten",
    about_subtitle: "Ons Verhaal", about_title_1: "Franse Elegantie", about_title_2: "Verheven door Expertise",
    about_p1: "Maison Oleria is geboren vanuit een diepe overtuiging: elk individu draagt een unieke elegantie in zich die alleen maar onthuld hoeft te worden.",
    about_p2: "Onze aanpak combineert professionele strengheid met persoonlijke warmte, waardoor elke transformatie een reis naar uw beste zelf wordt.",
    about_cta: "Ons Verhaal",
    services_subtitle: "Onze Expertise", services_title: "Beeldadvies Diensten",
    services_desc: "Volledige en persoonlijke begeleiding voor elk aspect van uw persoonlijk en professioneel imago.",
    services_cta: "Alle Diensten", discover: "Ontdekken",
    values_subtitle: "Onze Waarden", values_title_1: "Waarom Kiezen voor", values_title_2: "Maison Oleria",
    journey_subtitle: "Onze Methode", journey_title: "Uw Transformatiereis",
    testimonials_subtitle: "Getuigenissen", testimonials_title: "Wat Onze Klanten Zeggen",
    testimonials_cta: "Alle Getuigenissen",
    cta_title: "Klaar om Uw Stijl te Onthullen?", cta_desc: "Begin uw transformatie met een persoonlijk adviesgesprek.", cta_book: "Afspraak Boeken", cta_services: "Bekijk Pakketten",
    contact_subtitle: "Neem Contact Op", contact_title_1: "Uw Transformatie", contact_title_2: "Begint Hier",
    footer_tagline: "De kunst van het onthullen van uw unieke stijl via Franse elegantie.",
    stat_clients: "Getransformeerde Klanten", stat_years: "Jaar Ervaring", stat_satisfaction: "Klanttevredenheid", stat_services: "Maatdiensten",
    chat_title: "Maison Oleria", chat_subtitle: "Beeldadviseur", chat_greeting: "Hallo! Ik ben uw Maison Oleria adviseur. Hoe kan ik u vandaag helpen?",
    chat_placeholder: "Schrijf uw bericht...", chat_send: "Verzenden",
    chat_q1: "Welke dienst interesseert u?", chat_q2: "Meer over onze diensten", chat_q3: "Afspraak maken", chat_q4: "Prijzen en pakketten", chat_q5: "Stuur een bericht",
    chat_a_color: "Kleuranalyse", chat_a_styling: "Persoonlijke Styling", chat_a_pro: "Professioneel Imago", chat_a_wedding: "Bruidsstyling", chat_a_other: "Andere dienst",
    chat_name_ask: "Wat is uw voornaam?", chat_email_ask: "Uw e-mailadres?", chat_msg_ask: "Beschrijf uw vraag in enkele woorden:", chat_thanks: "Dank u! We nemen binnen 24 uur contact op. Tot snel!",
  },
  no: {
    nav_home: "Hjem", nav_about: "Om Oss", nav_services: "Tjenester",
    nav_testimonials: "Attester", nav_blog: "Blogg", nav_contact: "Kontakt",
    nav_consultation: "Konsultasjon",
    hero_subtitle: "Bilderadgivningshus",
    hero_title_1: "Kunsten a Avdekke",
    hero_title_2: "Din Naturlige",
    hero_title_3: "Eleganse",
    hero_desc: "Inspirert av tidlos fransk eleganse veileder Maison Oleria deg i a avdekke din unike stil.",
    hero_cta_1: "Bestill Time", hero_cta_2: "Oppdag Tjenestene",
    about_subtitle: "Var Historie", about_title_1: "Fransk Eleganse", about_title_2: "Loftet av Ekspertise",
    about_p1: "Maison Oleria ble skapt ut av en dyp overbevisning: hvert individ barer en unik eleganse i seg som bare venter pa a bli avdekket.",
    about_p2: "Var tilnaerming kombinerer profesjonell grundighet med personlig varme, slik at hver transformasjon blir en reise mot din beste versjon.",
    about_cta: "Var Historie",
    services_subtitle: "Var Ekspertise", services_title: "Bilderadgivningstjenester",
    services_desc: "Fullstendig og personlig veiledning for alle aspekter av ditt personlige og profesjonelle image.",
    services_cta: "Alle Tjenester", discover: "Oppdag",
    values_subtitle: "Vare Verdier", values_title_1: "Hvorfor Velge", values_title_2: "Maison Oleria",
    journey_subtitle: "Var Metode", journey_title: "Din Transformasjonsreise",
    testimonials_subtitle: "Attester", testimonials_title: "Hva Kundene Vare Sier",
    testimonials_cta: "Alle Attester",
    cta_title: "Klar til a Avdekke Din Stil?", cta_desc: "Start din transformasjon med en personlig konsultasjon.", cta_book: "Bestill Konsultasjon", cta_services: "Se Pakker",
    contact_subtitle: "Kontakt Oss", contact_title_1: "Din Transformasjon", contact_title_2: "Begynner Her",
    footer_tagline: "Kunsten a avdekke din unike stil gjennom fransk eleganse.",
    stat_clients: "Transformerte Kunder", stat_years: "Ars Erfaring", stat_satisfaction: "Kundetilfredshet", stat_services: "Skreddersydde Tjenester",
    chat_title: "Maison Oleria", chat_subtitle: "Bilderadgiver", chat_greeting: "Hei! Jeg er din Maison Oleria radgiver. Hvordan kan jeg hjelpe deg i dag?",
    chat_placeholder: "Skriv meldingen din...", chat_send: "Send",
    chat_q1: "Hvilken tjeneste interesserer deg?", chat_q2: "Laer mer om tjenestene", chat_q3: "Bestill time", chat_q4: "Priser og pakker", chat_q5: "Send melding",
    chat_a_color: "Fargeanalyse", chat_a_styling: "Personlig Styling", chat_a_pro: "Profesjonelt Image", chat_a_wedding: "Bryllupsstyling", chat_a_other: "Annen tjeneste",
    chat_name_ask: "Hva er fornavnet ditt?", chat_email_ask: "Din e-postadresse?", chat_msg_ask: "Beskriv forsporselen din med fa ord:", chat_thanks: "Takk! Vi kontakter deg innen 24 timer. Pa gjensyn!",
  },
  zh: {
    nav_home: "首页", nav_about: "关于我们", nav_services: "服务",
    nav_testimonials: "客户见证", nav_blog: "博客", nav_contact: "联系我们",
    nav_consultation: "预约咨询",
    hero_subtitle: "形象顾问工作室",
    hero_title_1: "揭示您",
    hero_title_2: "自然优雅",
    hero_title_3: "的艺术",
    hero_desc: "受法式永恒优雅的启发，Maison Oleria 帮助您发现独特的个人风格。",
    hero_cta_1: "预约咨询", hero_cta_2: "了解我们的服务",
    about_subtitle: "我们的故事", about_title_1: "法式优雅", about_title_2: "专业提升",
    about_p1: "Maison Oleria 源于一个深刻的信念：每个人都拥有独特的优雅，只需要被发现和展现。",
    about_p2: "我们的方法将专业严谨与个人温暖相结合，让每一次蜕变都成为通往最佳自我的旅程。",
    about_cta: "我们的故事",
    services_subtitle: "我们的专业", services_title: "形象顾问服务",
    services_desc: "针对个人和职业形象的每个方面提供全面、个性化的指导。",
    services_cta: "全部服务", discover: "了解更多",
    values_subtitle: "我们的价值观", values_title_1: "为何选择", values_title_2: "Maison Oleria",
    journey_subtitle: "我们的方法", journey_title: "您的蜕变之旅",
    testimonials_subtitle: "客户见证", testimonials_title: "客户的评价",
    testimonials_cta: "所有见证",
    cta_title: "准备好展现您的风格了吗？", cta_desc: "开始您的个性化咨询蜕变之旅。", cta_book: "预约咨询", cta_services: "查看套餐",
    contact_subtitle: "联系我们", contact_title_1: "您的蜕变", contact_title_2: "从这里开始",
    footer_tagline: "通过法式优雅，揭示您独特风格的艺术。",
    stat_clients: "转变客户", stat_years: "年经验", stat_satisfaction: "客户满意度", stat_services: "定制服务",
    chat_title: "Maison Oleria", chat_subtitle: "形象顾问", chat_greeting: "您好！我是您的 Maison Oleria 顾问。今天我能为您提供什么帮助？",
    chat_placeholder: "请输入您的消息...", chat_send: "发送",
    chat_q1: "您对哪项服务感兴趣？", chat_q2: "了解更多服务", chat_q3: "预约咨询", chat_q4: "价格和套餐", chat_q5: "发送消息",
    chat_a_color: "色彩分析", chat_a_styling: "个人造型", chat_a_pro: "职业形象", chat_a_wedding: "婚礼造型", chat_a_other: "其他服务",
    chat_name_ask: "请问您的名字？", chat_email_ask: "您的电子邮件地址？", chat_msg_ask: "请简单描述您的需求：", chat_thanks: "谢谢！我们将在24小时内与您联系。再见！",
  },
  ru: {
    nav_home: "Главная", nav_about: "О нас", nav_services: "Услуги",
    nav_testimonials: "Отзывы", nav_blog: "Блог", nav_contact: "Контакты",
    nav_consultation: "Консультация",
    hero_subtitle: "Дом имидж-консультирования",
    hero_title_1: "Искусство раскрыть",
    hero_title_2: "вашу природную",
    hero_title_3: "элегантность",
    hero_desc: "Вдохновленная вечной французской элегантностью, Maison Oleria помогает вам раскрыть уникальный стиль.",
    hero_cta_1: "Записаться на консультацию", hero_cta_2: "Узнать об услугах",
    about_subtitle: "Наша история", about_title_1: "Французская элегантность", about_title_2: "Возведенная мастерством",
    about_p1: "Maison Oleria родилась из глубокого убеждения: каждый человек несет в себе уникальную элегантность, которую нужно лишь раскрыть.",
    about_p2: "Наш подход сочетает профессиональный ригор с личной теплотой, делая каждое преображение путешествием к лучшей версии себя.",
    about_cta: "Наша история",
    services_subtitle: "Наша экспертиза", services_title: "Услуги имидж-консультирования",
    services_desc: "Полное и персонализированное сопровождение для каждого аспекта вашего личного и профессионального имиджа.",
    services_cta: "Все услуги", discover: "Узнать больше",
    values_subtitle: "Наши ценности", values_title_1: "Почему выбирают", values_title_2: "Maison Oleria",
    journey_subtitle: "Наш метод", journey_title: "Ваш путь преображения",
    testimonials_subtitle: "Отзывы", testimonials_title: "Что говорят наши клиенты",
    testimonials_cta: "Все отзывы",
    cta_title: "Готовы раскрыть свой стиль?", cta_desc: "Начните свое преображение с персональной консультации.", cta_book: "Записаться", cta_services: "Посмотреть пакеты",
    contact_subtitle: "Свяжитесь с нами", contact_title_1: "Ваше преображение", contact_title_2: "начинается здесь",
    footer_tagline: "Искусство раскрыть ваш уникальный стиль через французскую элегантность.",
    stat_clients: "Преображенных клиентов", stat_years: "Лет опыта", stat_satisfaction: "Удовлетворенность клиентов", stat_services: "Индивидуальных услуг",
    chat_title: "Maison Oleria", chat_subtitle: "Имидж-консультант", chat_greeting: "Здравствуйте! Я ваш консультант Maison Oleria. Чем могу помочь сегодня?",
    chat_placeholder: "Напишите сообщение...", chat_send: "Отправить",
    chat_q1: "Какая услуга вас интересует?", chat_q2: "Узнать об услугах", chat_q3: "Записаться на консультацию", chat_q4: "Цены и пакеты", chat_q5: "Отправить сообщение",
    chat_a_color: "Цветовой анализ", chat_a_styling: "Персональный стайлинг", chat_a_pro: "Профессиональный имидж", chat_a_wedding: "Свадебный стайлинг", chat_a_other: "Другая услуга",
    chat_name_ask: "Как вас зовут?", chat_email_ask: "Ваш email?", chat_msg_ask: "Опишите ваш запрос кратко:", chat_thanks: "Спасибо! Мы свяжемся с вами в течение 24 часов. До скорой встречи!",
  },
  ar: {
    nav_home: "الرئيسية", nav_about: "من نحن", nav_services: "الخدمات",
    nav_testimonials: "الشهادات", nav_blog: "المدونة", nav_contact: "اتصل بنا",
    nav_consultation: "استشارة",
    hero_subtitle: "دار استشارات الصورة",
    hero_title_1: "فن الكشف عن",
    hero_title_2: "أناقتك",
    hero_title_3: "الطبيعية",
    hero_desc: "مستوحاة من الأناقة الفرنسية الخالدة، تصحبك Maison Oleria في الكشف عن أسلوبك الفريد.",
    hero_cta_1: "احجز موعدًا", hero_cta_2: "اكتشف خدماتنا",
    about_subtitle: "قصتنا", about_title_1: "الأناقة الفرنسية", about_title_2: "مرفوعة بالخبرة",
    about_p1: "وُلدت Maison Oleria من قناعة عميقة: كل فرد يحمل في داخله أناقة فريدة تنتظر فقط أن تُكشف.",
    about_p2: "يجمع نهجنا بين الصرامة المهنية والدفء الشخصي، مما يجعل كل تحول رحلة نحو أفضل نسخة منك.",
    about_cta: "قصتنا",
    services_subtitle: "خبرتنا", services_title: "خدمات استشارات الصورة",
    services_desc: "مرافقة كاملة وشخصية لكل جانب من جوانب صورتك الشخصية والمهنية.",
    services_cta: "جميع الخدمات", discover: "اكتشف",
    values_subtitle: "قيمنا", values_title_1: "لماذا تختار", values_title_2: "Maison Oleria",
    journey_subtitle: "منهجنا", journey_title: "رحلة تحولك",
    testimonials_subtitle: "الشهادات", testimonials_title: "ما يقوله عملاؤنا",
    testimonials_cta: "جميع الشهادات",
    cta_title: "هل أنت مستعدة للكشف عن أسلوبك؟", cta_desc: "ابدئي تحولك بجلسة استشارية شخصية.", cta_book: "احجزي استشارتي", cta_services: "انظري باقاتنا",
    contact_subtitle: "تواصل معنا", contact_title_1: "تحولك", contact_title_2: "يبدأ هنا",
    footer_tagline: "فن الكشف عن أسلوبك الفريد من خلال الأناقة الفرنسية.",
    stat_clients: "عميل تحول", stat_years: "سنوات خبرة", stat_satisfaction: "رضا العملاء", stat_services: "خدمات مخصصة",
    chat_title: "Maison Oleria", chat_subtitle: "مستشارة الصورة", chat_greeting: "مرحبًا! أنا مستشارتك في Maison Oleria. كيف يمكنني مساعدتك اليوم؟",
    chat_placeholder: "اكتبي رسالتك...", chat_send: "إرسال",
    chat_q1: "أي خدمة تهمك؟", chat_q2: "معرفة المزيد عن خدماتنا", chat_q3: "حجز موعد", chat_q4: "الأسعار والباقات", chat_q5: "إرسال رسالة",
    chat_a_color: "تحليل الألوان", chat_a_styling: "التصميم الشخصي", chat_a_pro: "الصورة المهنية", chat_a_wedding: "تصميم الزفاف", chat_a_other: "خدمة أخرى",
    chat_name_ask: "ما هو اسمك الأول؟", chat_email_ask: "عنوان بريدك الإلكتروني؟", chat_msg_ask: "صفي طلبك بكلمات قليلة:", chat_thanks: "شكرًا لك! سنتواصل معك خلال 24 ساعة. إلى اللقاء!",
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: TranslationKey) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "fr",
  setLang: () => {},
  t: (key) => key,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<LangCode>("fr");
  const dir = LANGUAGES.find((l) => l.code === lang)?.dir ?? "ltr";
  const t = (key: TranslationKey) => T[lang][key] ?? T["fr"][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
